config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  get '/about', to: 'pages#about'
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:name, :body, :post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def show
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'New post created'
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post updated'
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Post deleted'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>
  <% if user_signed_in? %>
    <p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: 'button', data: { confirm: 'Are you sure?' } %></p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :body, class: 'form-label' %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div>
    <%= f.submit 'Save Comment', class: 'button' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tumblr</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= favicon_link_tag('favicon.png') %>
</head>

<body>

<!--<p class="notice"><%#= notice %></p>
<p class="alert"><%#= alert %></p>-->

<div id="sidebar">
  <ul>
    <li class="category"><%= link_to "Tumblr", root_path %></li>
    <li><%= link_to "Posts", root_path %></li>
    <li><%= link_to 'About', about_path %></li>
  </ul>
  <% unless user_signed_in? %>
    <p class="sign_in"><%= link_to 'User Login', new_user_session_path %></p>
  <% end %>
</div>

<div id="main_content">
  <div id="header">
    <% if current_page?(root_path) %>
      <p>Post Feed</p>
    <% elsif current_page?(about_path) %>
      <p>My Site</p>
    <% else %>
      <%= link_to "Back to post feed", root_path %>
    <% end %>

    <% if user_signed_in? %>
      <div class="buttons">
        <button class="button"><%= link_to "Make post", new_post_path %></button>
        <button class="button"><%= link_to 'Log Out', destroy_user_session_path, method:  :delete %></button>
      </div>
    <% end %>
  </div>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: 'alert') %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpeg" %>
  </div>

  <div id="content">
    <h1>It's Mr. Stick Figure</h1>
    <p>
      Morbi dignissim malesuada nibh, eu commodo dolor placerat posuere. Sed accumsan malesuada lacus quis malesuada.
      Mauris finibus diam nulla, ut ultricies leo lacinia quis. Phasellus vel maximus odio. Vestibulum sed fringilla
      eros. Praesent gravida metus ut sem elementum, et hendrerit nisl sodales. Cras gravida tempor turpis quis
      accumsan. Donec ut facilisis ex.
    </p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :title, class: 'form-label' %> <br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :body, class: "form-label" %> <br>
    <%= f.text_area :body, rows: '10', class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.submit 'Save Post', class: 'button' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h2>Edit</h2>
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="body"><%= truncate(post.body, length: 100) %></p>
    <p class="date"><%= time_ago_in_words(post.created_at) %> ago</p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h2>New</h2>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h2 class="title"><%= @post.title %></h2>
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago
    <% if user_signed_in? %>
      |
      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <p class="body"><%= @post.body %></p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3>Join Discussion:</h3>
    <%= render 'comments/form' %>
  </div>
</div>